name: container-images


on:
  push:
    branches: [ "acex-production", "acex-test" ]
    tags: [ "v*" ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: docker/setup-qemu-action@v3
    - uses: docker/setup-buildx-action@v3

    - run: echo "IMAGE_TAG=acex-production" >> $GITHUB_ENV
      if: github.ref_name == 'acex-production'
    - run: echo "IMAGE_TAG=acex-test" >> $GITHUB_ENV
      if: github.ref_name == 'acex-test'
    - run: echo "IMAGE_TAG=${GITHUB_REF##*/}" >> $GITHUB_ENV
      if: startsWith(github.ref, 'refs/tags/v')

    - name: Login to ghcr.io
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Login to docker.io
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_UID }}
        password: ${{ secrets.DOCKER_HUB_PAT }}

    - name: Build image
      run: |        
        docker buildx build \
          --platform linux/amd64,linux/arm64,linux/arm/v7 \
          --tag ghcr.io/${{ github.repository }}:${{ env.IMAGE_TAG }} \
          --file ./Dockerfile \
          --output type=image,push=true .
